# Generated by Django 5.0.4 on 2024-04-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_type', models.TextField(choices=[('TE', 'TEXT FIELD'), ('NU', 'NUMBER FIELD'), ('RA', 'RADIO FIELD'), ('TA', 'TEXT AREA')])),
                ('icon', models.TextField()),
            ],
        ),
    ]
