# Generated by Django 5.0.4 on 2024-04-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_legendvideo_profile_projectcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legendvideo',
            name='title',
            field=models.CharField(default='Current Video', max_length=100),
        ),
    ]
