# Generated by Django 5.0.4 on 2024-04-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_compareslider_legendvideo_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('descritption', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.AddField(
            model_name='compareslider',
            name='services_one',
            field=models.ManyToManyField(related_name='first_slide', to='promo.service'),
        ),
        migrations.AddField(
            model_name='compareslider',
            name='services_two',
            field=models.ManyToManyField(related_name='second_slide', to='promo.service'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='promo.service'),
        ),
    ]
