# Generated by Django 5.0.4 on 2024-04-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_service_delete_projectcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compareslider',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
