# Generated by Django 5.0.4 on 2024-04-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0007_project_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='categories',
            new_name='services',
        ),
    ]
