# Generated by Django 5.0.4 on 2024-04-15 14:32

import django.core.validators
import django.db.models.deletion
import promo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0008_rename_categories_project_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=promo.models.ProjectMedia.project_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'mp4', 'avi', 'mkv'])])),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='promo.project')),
            ],
        ),
    ]
