# Generated by Django 5.0.4 on 2024-04-16 12:09

import promo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0009_projectmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('client_type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=promo.models.Testimonial.testimonial_directory_path)),
            ],
        ),
    ]
