# Generated by Django 5.0.4 on 2024-04-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0011_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.IntegerField()),
                ('to_value', models.IntegerField()),
            ],
        ),
    ]
