# Generated by Django 5.0.4 on 2024-04-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0012_budgetrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
    ]
