# Generated by Django 5.0.4 on 2024-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0013_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
