# Generated by Django 5.0.4 on 2024-04-25 11:51

import promo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0014_page_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_legend', models.ImageField(upload_to=promo.models.AboutContent.upload_legend)),
                ('legend_title', models.CharField(max_length=100)),
                ('legend_text', models.TextField()),
                ('text_one', models.TextField()),
                ('text_two', models.TextField(blank=True, null=True)),
                ('text_three', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
    ]
