# Generated by Django 5.0.4 on 2024-04-28 15:06

import promo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0016_frequentlyaskedquestion_term_aboutcontent_title_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=promo.models.Service.service_upload),
        ),
    ]
