# Generated by Django 5.0.4 on 2024-04-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0017_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
