# Generated by Django 5.0.4 on 2024-04-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0018_aboutcontent_datetime_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='descritption',
            new_name='description',
        ),
    ]
