# Generated by Django 5.0.4 on 2024-05-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0019_rename_descritption_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('icon', models.TextField()),
            ],
        ),
    ]
