# Generated by Django 5.0.4 on 2024-05-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0021_socialmediaaccount_delete_socialaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='base_url',
            field=models.URLField(),
        ),
    ]
