# Generated by Django 5.0.4 on 2024-05-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0022_alter_socialmediaaccount_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
