# Generated by Django 5.0.4 on 2024-05-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0026_category_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compareslider',
            name='services_one',
        ),
        migrations.RemoveField(
            model_name='compareslider',
            name='services_two',
        ),
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
        migrations.AddField(
            model_name='compareslider',
            name='categories_one',
            field=models.ManyToManyField(related_name='first_slide', to='promo.category'),
        ),
        migrations.AddField(
            model_name='compareslider',
            name='categories_two',
            field=models.ManyToManyField(related_name='second_slide', to='promo.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='promo.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_consignments',
            field=models.ManyToManyField(related_name='sellers_profiles', to='promo.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested_services',
            field=models.ManyToManyField(related_name='buyers_profiles', to='promo.category'),
        ),
    ]
