# Generated by Django 5.0.4 on 2024-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0027_remove_compareslider_services_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default='NOT PROVIDED', max_length=16),
        ),
    ]
